//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace darker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("darker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_AboutGroupHeader {
            get {
                return ResourceManager.GetString("About_AboutGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string About_AppGroupHeader {
            get {
                return ResourceManager.GetString("About_AppGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roman Linev.
        /// </summary>
        public static string About_AuthorNameText {
            get {
                return ResourceManager.GetString("About_AuthorNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is completely free and open-source. .
        /// </summary>
        public static string About_SupportBodyText {
            get {
                return ResourceManager.GetString("About_SupportBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string About_SupportGroupHeader {
            get {
                return ResourceManager.GetString("About_SupportGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit the project page on.
        /// </summary>
        public static string About_VisitGHLinkText {
            get {
                return ResourceManager.GetString("About_VisitGHLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can configure a way to switch a theme mode from keyboard.
        ///.
        /// </summary>
        public static string Advanced_HotKeyBodyText {
            get {
                return ResourceManager.GetString("Advanced_HotKeyBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom hotkey combination:.
        /// </summary>
        public static string Advanced_HotKeyBoxHeader {
            get {
                return ResourceManager.GetString("Advanced_HotKeyBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard shortcuts.
        /// </summary>
        public static string Advanced_HotKeyGroupHeader {
            get {
                return ResourceManager.GetString("Advanced_HotKeyGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom hotkeys are disabled in this version, use the default one..
        /// </summary>
        public static string Advanced_HotKeyNotImplementedText {
            get {
                return ResourceManager.GetString("Advanced_HotKeyNotImplementedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable hotkeys.
        /// </summary>
        public static string Advanced_HotKeyToggleHeader {
            get {
                return ResourceManager.GetString("Advanced_HotKeyToggleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you find that some theme settings are off, you can use this button to reset everything to Windows 10 default theme..
        /// </summary>
        public static string Advanced_TrobleshootingBodyText {
            get {
                return ResourceManager.GetString("Advanced_TrobleshootingBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trobleshooting.
        /// </summary>
        public static string Advanced_TrobleshootingGroupHeader {
            get {
                return ResourceManager.GetString("Advanced_TrobleshootingGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset theme.
        /// </summary>
        public static string Advanced_TroubleshootingThemeResetButton {
            get {
                return ResourceManager.GetString("Advanced_TroubleshootingThemeResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme settings.
        /// </summary>
        public static string Advanced_TroubleshootingThemeSettingsLink {
            get {
                return ResourceManager.GetString("Advanced_TroubleshootingThemeSettingsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to darker.
        /// </summary>
        public static string App_AppName {
            get {
                return ResourceManager.GetString("App_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file is not accessible. Please consider moving the app to another directory..
        /// </summary>
        public static string Error_FileAccessErrorMessage {
            get {
                return ResourceManager.GetString("Error_FileAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is designed for Windows 10 only. Please consider upgrading your OS..
        /// </summary>
        public static string Error_OSVersionMessage {
            get {
                return ResourceManager.GetString("Error_OSVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured.
        /// </summary>
        public static string Error_PopupTitle {
            get {
                return ResourceManager.GetString("Error_PopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is already running..
        /// </summary>
        public static string Error_RunningAppMessage {
            get {
                return ResourceManager.GetString("Error_RunningAppMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run at startup.
        /// </summary>
        public static string General_AppAutoStartToggleHeader {
            get {
                return ResourceManager.GetString("General_AppAutoStartToggleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow automatic updates.
        /// </summary>
        public static string General_AppAutoUpdateToggleHeader {
            get {
                return ResourceManager.GetString("General_AppAutoUpdateToggleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string General_AppSetingsGroupHeader {
            get {
                return ResourceManager.GetString("General_AppSetingsGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure what clicking on the tray icon actually does. Try every option to choose the right one for you..
        /// </summary>
        public static string General_BehaveBodyText {
            get {
                return ResourceManager.GetString("General_BehaveBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default behavior:.
        /// </summary>
        public static string General_BehaveBoxHeader {
            get {
                return ResourceManager.GetString("General_BehaveBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        public static string General_BehaveGroupHeader {
            get {
                return ResourceManager.GetString("General_BehaveGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System and apps.
        /// </summary>
        public static string General_BoxItemChangeBoth {
            get {
                return ResourceManager.GetString("General_BoxItemChangeBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only apps.
        /// </summary>
        public static string General_BoxItemChangeOnlyApp {
            get {
                return ResourceManager.GetString("General_BoxItemChangeOnlyApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only system.
        /// </summary>
        public static string General_BoxItemChangeOnlySys {
            get {
                return ResourceManager.GetString("General_BoxItemChangeOnlySys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your mode.
        /// </summary>
        public static string General_BoxPlaceholderText {
            get {
                return ResourceManager.GetString("General_BoxPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Main_MenuExitButton {
            get {
                return ResourceManager.GetString("Main_MenuExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Main_MenuSettingsButton {
            get {
                return ResourceManager.GetString("Main_MenuSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Nav_AboutTab {
            get {
                return ResourceManager.GetString("Nav_AboutTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Nav_AdvancedTab {
            get {
                return ResourceManager.GetString("Nav_AdvancedTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Nav_GeneralTab {
            get {
                return ResourceManager.GetString("Nav_GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Nav_WindowTitle {
            get {
                return ResourceManager.GetString("Nav_WindowTitle", resourceCulture);
            }
        }
    }
}
